#!/usr/bin/env python3
"""
gen_test_vectors.py — Ground-truth FK and IK test vector generator.

Uses modern_robotics (Lynch & Park) as the reference implementation.
Reads robot_config.yaml and writes:
  - validation/fk_test_vectors.json             (human-readable FK ground truth)
  - tests/kinematics/include/fk_test_vectors.h  (embedded in C native FK tests)
  - validation/ik_test_vectors.json             (human-readable IK ground truth)
  - tests/kinematics/include/ik_test_vectors.h  (embedded in C native IK tests)

Usage:
    cd validation
    python gen_test_vectors.py
    # then: make test-native
"""

import json
import os
from datetime import date

import numpy as np
import yaml
import modern_robotics as mr

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT   = os.path.dirname(SCRIPT_DIR)

YAML_PATH   = os.path.join(SCRIPT_DIR, "robot_config.yaml")
JSON_OUT    = os.path.join(SCRIPT_DIR, "fk_test_vectors.json")
HEADER_OUT  = os.path.join(REPO_ROOT, "tests", "kinematics", "include",
                            "fk_test_vectors.h")

# ---------------------------------------------------------------------------
# Load robot config
# ---------------------------------------------------------------------------

with open(YAML_PATH) as f:
    cfg = yaml.safe_load(f)

Slist = np.array(cfg["screw_axes"], dtype=float).T   # (6, n_joints)
M     = np.array(cfg["home_config"], dtype=float)    # (4, 4)
N     = cfg["num_joints"]

assert Slist.shape == (6, N), f"Expected Slist (6,{N}), got {Slist.shape}"
assert M.shape == (4, 4)

# Sanity: FK(zero) must equal M
T_zero = mr.FKinSpace(M, Slist, np.zeros(N))
assert np.allclose(T_zero, M, atol=1e-9), "FK(zero) != M — check robot_config.yaml"

# ---------------------------------------------------------------------------
# Build test cases
# ---------------------------------------------------------------------------

def fk(theta):
    return mr.FKinSpace(M, Slist, np.asarray(theta, dtype=float))


cases = []


def add(theta, label):
    T = fk(theta)
    cases.append({"description": label,
                  "theta": list(theta),
                  "T_expected": T.tolist()})


# Zero config
add([0.0] * N, "zero_config")

# Single-joint sweeps: each joint at +30° and -30°
for j in range(N):
    for deg, sign in [(30, "pos"), (-30, "neg")]:
        th = [0.0] * N
        th[j] = np.deg2rad(deg)
        add(th, f"j{j}_{sign}30")

# Single-joint edge angles for joint 0 (base, easiest to reason about)
for deg, label in [(90, "pos90"), (-90, "neg90"), (180, "pos180")]:
    th = [0.0] * N
    th[0] = np.deg2rad(deg)
    add(th, f"j0_{label}")

# Adjacent-joint pairs
pairs = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]
for (a, b) in pairs:
    th = [0.0] * N
    th[a] = np.deg2rad(30)
    th[b] = np.deg2rad(-20)
    add(th, f"j{a}j{b}_30_neg20")

# All joints simultaneously
add([np.deg2rad(d) for d in [10, -20, 30, -40, 50, -60]], "all_joints_mixed")
add([np.deg2rad(30)] * N, "all_joints_30deg")

# Random configs (reproducible seeds)
for seed in range(12):
    rng = np.random.default_rng(seed)
    th = rng.uniform(-np.pi / 2, np.pi / 2, size=N)
    add(list(th), f"rng_seed{seed}")

print(f"Generated {len(cases)} test vectors.")

# ---------------------------------------------------------------------------
# Write JSON
# ---------------------------------------------------------------------------

with open(JSON_OUT, "w") as f:
    json.dump({"robot": "mecharm_270_pi",
               "generated": str(date.today()),
               "num_vectors": len(cases),
               "test_vectors": cases}, f, indent=2)

print(f"Wrote {JSON_OUT}")

# ---------------------------------------------------------------------------
# Write C header
# ---------------------------------------------------------------------------

def fmt_float(v):
    """Format float for C: 8 significant digits, always has decimal point."""
    return f"{v:.8f}f"


def fmt_theta(theta):
    return "{" + ", ".join(fmt_float(t) for t in theta) + "}"


def fmt_mat(T):
    rows = []
    for r in range(4):
        row = "        {" + ", ".join(fmt_float(T[r][c]) for c in range(4)) + "}"
        rows.append(row)
    return "{\n" + ",\n".join(rows) + "\n    }"


os.makedirs(os.path.dirname(HEADER_OUT), exist_ok=True)

lines = [
    "/* Auto-generated by validation/gen_test_vectors.py — do not edit */",
    f"/* Robot: mecharm_270_pi  |  Generated: {date.today()} */",
    "#ifndef FK_TEST_VECTORS_H",
    "#define FK_TEST_VECTORS_H",
    "",
    "#include <stddef.h>",
    "",
    f"#define NUM_FK_TEST_VECTORS {len(cases)}",
    "",
    "typedef struct {",
    "    float theta[6];",
    "    float T_expected[4][4];",
    "    const char *description;",
    "} fk_test_vector_t;",
    "",
    "static const fk_test_vector_t FK_TEST_VECTORS[NUM_FK_TEST_VECTORS] = {",
]

for i, c in enumerate(cases):
    lines.append(f"    /* [{i}] {c['description']} */")
    lines.append("    {")
    lines.append(f"        .theta = {fmt_theta(c['theta'])},")
    lines.append(f"        .T_expected = {fmt_mat(np.array(c['T_expected']))},")
    lines.append(f"        .description = \"{c['description']}\"")
    sep = "," if i < len(cases) - 1 else ""
    lines.append(f"    }}{sep}")

lines += [
    "};",
    "",
    "#endif /* FK_TEST_VECTORS_H */",
    "",
]

with open(HEADER_OUT, "w") as f:
    f.write("\n".join(lines))

print(f"Wrote {HEADER_OUT}")

# ---------------------------------------------------------------------------
# IK ground-truth vectors (body-frame IKinBody)
# ---------------------------------------------------------------------------

IK_HEADER_OUT = os.path.join(REPO_ROOT, "tests", "kinematics", "include",
                             "ik_test_vectors.h")

# Body screw list: B_i = Ad_{M^-1} * S_i  (columns are body screw axes).
Blist = mr.Adjoint(mr.TransInv(M)) @ Slist  # (6, N)

IK_EOMG = 1e-3
IK_EV = 1e-4

ik_cases = []


def add_ik(theta_true, label, rng):
    theta_true = np.asarray(theta_true, dtype=float)
    T_target = mr.FKinSpace(M, Slist, theta_true)
    seed = theta_true + rng.uniform(-0.1, 0.1, size=N)
    theta_sol, ok = mr.IKinBody(Blist, M, T_target, seed.copy(),
                                IK_EOMG, IK_EV)
    ik_cases.append({"description": label,
                     "seed": list(seed),
                     "T_target": T_target.tolist(),
                     "theta_ref": list(theta_sol),
                     "converged": bool(ok)})


# Home + reproducible random reachable configs (seed perturbed from truth).
add_ik([0.0] * N, "ik_home", np.random.default_rng(100))
for seed_id in range(12):
    rng = np.random.default_rng(200 + seed_id)
    th = rng.uniform(-np.pi / 3, np.pi / 3, size=N)
    add_ik(list(th), f"ik_rng_seed{seed_id}", rng)

n_conv = sum(1 for c in ik_cases if c["converged"])
print(f"Generated {len(ik_cases)} IK vectors ({n_conv} converged).")

# ---------------------------------------------------------------------------
# Write IK JSON
# ---------------------------------------------------------------------------

IK_JSON_OUT = os.path.join(SCRIPT_DIR, "ik_test_vectors.json")
with open(IK_JSON_OUT, "w") as f:
    json.dump({"robot": "mecharm_270_pi",
               "generated": str(date.today()),
               "num_vectors": len(ik_cases),
               "eomg": IK_EOMG,
               "ev": IK_EV,
               "ik_vectors": ik_cases}, f, indent=2)
print(f"Wrote {IK_JSON_OUT}")

# ---------------------------------------------------------------------------
# Write IK C header
# ---------------------------------------------------------------------------

ik_lines = [
    "/* Auto-generated by validation/gen_test_vectors.py — do not edit */",
    f"/* Robot: mecharm_270_pi  |  Generated: {date.today()} */",
    "#ifndef IK_TEST_VECTORS_H",
    "#define IK_TEST_VECTORS_H",
    "",
    "#include <stddef.h>",
    "",
    f"#define NUM_IK_TEST_VECTORS {len(ik_cases)}",
    "",
    "typedef struct {",
    "    float seed[6];",
    "    float T_target[4][4];",
    "    float theta_ref[6];",
    "    int converged;",
    "    const char *description;",
    "} ik_test_vector_t;",
    "",
    "static const ik_test_vector_t IK_TEST_VECTORS[NUM_IK_TEST_VECTORS] = {",
]

for i, c in enumerate(ik_cases):
    ik_lines.append(f"    /* [{i}] {c['description']} */")
    ik_lines.append("    {")
    ik_lines.append(f"        .seed = {fmt_theta(c['seed'])},")
    ik_lines.append(f"        .T_target = {fmt_mat(np.array(c['T_target']))},")
    ik_lines.append(f"        .theta_ref = {fmt_theta(c['theta_ref'])},")
    ik_lines.append(f"        .converged = {1 if c['converged'] else 0},")
    ik_lines.append(f"        .description = \"{c['description']}\"")
    sep = "," if i < len(ik_cases) - 1 else ""
    ik_lines.append(f"    }}{sep}")

ik_lines += ["};", "", "#endif /* IK_TEST_VECTORS_H */", ""]

with open(IK_HEADER_OUT, "w") as f:
    f.write("\n".join(ik_lines))

print(f"Wrote {IK_HEADER_OUT}")
